// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerError defines model for ServerError.
type ServerError struct {
	// Error エラーコード
	Error *string `json:"error,omitempty"`

	// Message エラーメッセージ
	Message *string `json:"message,omitempty"`
}

// Stream defines model for Stream.
type Stream struct {
	// CreatedAt 作成日時
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Description 配信の説明
	Description *string `json:"description,omitempty"`

	// StreamID 配信ID
	StreamID *string `json:"streamId,omitempty"`

	// Title 配信タイトル
	Title *string `json:"title,omitempty"`

	// UserID ユーザーID
	UserID *string `json:"userId,omitempty"`
}

// StreamSummary defines model for StreamSummary.
type StreamSummary struct {
	// CreatedAt 作成日時
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// StreamID 配信ID
	StreamID *string `json:"streamId,omitempty"`

	// Title 配信タイトル
	Title *string `json:"title,omitempty"`

	// UserID ユーザーID
	UserID *string `json:"userId,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Details フィールドごとのエラー詳細
	Details *[]struct {
		// Field エラーが発生したフィールド名
		Field *string `json:"field,omitempty"`

		// Message エラーの詳細メッセージ
		Message *string `json:"message,omitempty"`
	} `json:"details,omitempty"`

	// Error エラーコード
	Error *string `json:"error,omitempty"`

	// Message エラーメッセージ
	Message *string `json:"message,omitempty"`
}

// PostAPIV1StreamsJSONBody defines parameters for PostAPIV1Streams.
type PostAPIV1StreamsJSONBody struct {
	// Description 概要欄の内容
	Description string `json:"description"`

	// Title 配信タイトル
	Title string `json:"title"`

	// UserID ユーザーID
	UserID string `json:"userId"`
}

// PostAPIV1StreamsJSONRequestBody defines body for PostAPIV1Streams for application/json ContentType.
type PostAPIV1StreamsJSONRequestBody PostAPIV1StreamsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// YouTube配信情報の一覧取得
	// (GET /api/v1/streams)
	GetAPIV1Streams(w http.ResponseWriter, r *http.Request)
	// YouTube配信情報の登録
	// (POST /api/v1/streams)
	PostAPIV1Streams(w http.ResponseWriter, r *http.Request)
	// YouTube配信情報の削除
	// (DELETE /api/v1/streams/{streamId})
	DeleteAPIV1StreamsStreamID(w http.ResponseWriter, r *http.Request, streamID string)
	// YouTube配信情報の詳細取得
	// (GET /api/v1/streams/{streamId})
	GetAPIV1StreamsStreamID(w http.ResponseWriter, r *http.Request, streamID string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// YouTube配信情報の一覧取得
// (GET /api/v1/streams)
func (_ Unimplemented) GetAPIV1Streams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// YouTube配信情報の登録
// (POST /api/v1/streams)
func (_ Unimplemented) PostAPIV1Streams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// YouTube配信情報の削除
// (DELETE /api/v1/streams/{streamId})
func (_ Unimplemented) DeleteAPIV1StreamsStreamID(w http.ResponseWriter, r *http.Request, streamID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// YouTube配信情報の詳細取得
// (GET /api/v1/streams/{streamId})
func (_ Unimplemented) GetAPIV1StreamsStreamID(w http.ResponseWriter, r *http.Request, streamID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAPIV1Streams operation middleware
func (siw *ServerInterfaceWrapper) GetAPIV1Streams(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAPIV1Streams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAPIV1Streams operation middleware
func (siw *ServerInterfaceWrapper) PostAPIV1Streams(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAPIV1Streams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAPIV1StreamsStreamID operation middleware
func (siw *ServerInterfaceWrapper) DeleteAPIV1StreamsStreamID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "streamId" -------------
	var streamID string

	err = runtime.BindStyledParameterWithOptions("simple", "streamId", chi.URLParam(r, "streamId"), &streamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "streamId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAPIV1StreamsStreamID(w, r, streamID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAPIV1StreamsStreamID operation middleware
func (siw *ServerInterfaceWrapper) GetAPIV1StreamsStreamID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "streamId" -------------
	var streamID string

	err = runtime.BindStyledParameterWithOptions("simple", "streamId", chi.URLParam(r, "streamId"), &streamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "streamId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAPIV1StreamsStreamID(w, r, streamID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/streams", wrapper.GetAPIV1Streams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/streams", wrapper.PostAPIV1Streams)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/streams/{streamId}", wrapper.DeleteAPIV1StreamsStreamID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/streams/{streamId}", wrapper.GetAPIV1StreamsStreamID)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RX604bxxd/FXT+/48LuyYgof2WKFGF1A+RiFK1FYom9gAb7a0zYxSELHV36pRbEpQm",
	"UJRIQMstgTpp6CUtNDzMsAt+i2pmbbC9a6ehtCqthIx3vHvOmfO7nNlJyHuO77nYZRTMSaD5Mewg9XUI",
	"k3FMrhHiEXnpE8/HhFlY/YjrywVM88TymeW5YIIItwR/Lvi+CHflJ58GDfBd5Pg2BhMsl2HiIvsWVbFv",
	"JVE0YBO+/JkyYrmjUNLAwZSiUdwpAV8VnItwTyV705RGhD+qO+YF34/ulat8SwSbp08Gc0dLvx49XhbB",
	"ogjeqs/ldBGlkxXv9h2cZ7KsIUYwctLdyBOMGC5cZumCD397Fk/Nx4vr8VLYVGSv0dvfnevtNgZu5AzT",
	"kH+fgAYjHnEQAxMKiOFuZjk4qz9NOVpTVsv3Dw9WRVA5frETf/2gpTWvVWtWospyvBuI8FG9C0tZeaja",
	"8GChXZLBq03Rc1kxmMVs3LbK8ECEa4JPCb7dFOpwbyZeXBdBRYIm71hIHsjKUKSYZNUo+IZix0+C77+7",
	"0vaADxUdB5GJ88a9q+sMyP/XEbmJbKuAZLg2zlTADFk2zcr9RITfKvZvCz4tgsci2JLbqRvD8fPdox9e",
	"gQYWww5NRx6xsF3oZElNxrLcki+av9+03wSEs3lfUElq7WyCpziK4GV0UK6uTEkfzFJ6VqdrC4gQNCGv",
	"z2b54yd4/VVuH5XXo5mn0b1yVPlFBNvRk4fV1TkRzIkgFOFMO29L71guWe6IJ8uoKQQ+unalK2cY8bMd",
	"wR+oCl6CBuOY0KTAXI8hN+D52EW+BSZc6jF6LoEGPmJjijQ68i19PKcnulVLo1j5haSWaowUCnyA2eXr",
	"gzdzQ7X7NCCY+p5LE+71GoYyHM9l2FWPI9+3rbwKoN+hyRxIpneauQ3JT7j9f4JHwIT/6acHAL02/fVm",
	"20txIbt3zdBFDxeit4vx1Hw0sywj9L/nBjqW13AyyUidMf7rPFK107qdw8de8UbxNk58LOblaOV7EVQO",
	"33x+vLGZbEASB41SMD+FxrtguKSB79EMIK97NI3kZ0VM2RWvMPEnQOw48+ON8HgjiHe+EEElkcJ7jH0H",
	"3f0Qu6NsDMx+w7jYA0P22iK4IBGrBdVOvLYx9nAmiU8fZ6SISykV5s6PxMlZMoO/taPDiXT6zlE6reMz",
	"Sz5SOC8E/1I1/mfBNwXfbVDQhdLy0dJede51exWXtFaH1ifrR6xSQkcbM5yW+VW13ij05J8iqY8IcjDD",
	"RKbscE6z5LUcFaCBi5walZPzXSsXtYaGttJ+OMXTvrSUoumZ6tJaI6362r87zB1vzIpgTQSz9Rn6VIRf",
	"XTDwkx13svA/Mor/Ubgaf4P/tI7ufz9RktP0uya+iqQKyYJf8O+UYW4Lvl1dmJVvAo9eRd9w0KBIbDBh",
	"jDHf1HXbyyN7zKPMHDAGDB1Kw6XfAwAA//9DpLmHhREAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
